export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          phone: string | null;
          name: string | null;
          image: string | null;
          role: UserRole;
          email_verified: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          phone?: string | null;
          name?: string | null;
          image?: string | null;
          role?: UserRole;
          email_verified?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          phone?: string | null;
          name?: string | null;
          image?: string | null;
          role?: UserRole;
          email_verified?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image: string | null;
          parent_id: string | null;
          order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          image?: string | null;
          parent_id?: string | null;
          order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          image?: string | null;
          parent_id?: string | null;
          order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      fabrics: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          material: string | null;
          composition: string | null;
          weight: string | null;
          texture: string | null;
          pattern: string | null;
          color: string | null;
          color_hex: string | null;
          image: string | null;
          images: string | null;
          price_per_meter: number;
          stock_quantity: number;
          min_order: number;
          origin: string | null;
          quality: FabricQuality;
          is_active: boolean;
          is_premium: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          material?: string | null;
          composition?: string | null;
          weight?: string | null;
          texture?: string | null;
          pattern?: string | null;
          color?: string | null;
          color_hex?: string | null;
          image?: string | null;
          images?: string | null;
          price_per_meter: number;
          stock_quantity?: number;
          min_order?: number;
          origin?: string | null;
          quality?: FabricQuality;
          is_active?: boolean;
          is_premium?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          material?: string | null;
          composition?: string | null;
          weight?: string | null;
          texture?: string | null;
          pattern?: string | null;
          color?: string | null;
          color_hex?: string | null;
          image?: string | null;
          images?: string | null;
          price_per_meter?: number;
          stock_quantity?: number;
          min_order?: number;
          origin?: string | null;
          quality?: FabricQuality;
          is_active?: boolean;
          is_premium?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          category_id: string | null;
          product_type: ProductType;
          base_price: number;
          is_active: boolean;
          is_featured: boolean;
          is_new: boolean;
          images: string | null;
          thumbnail: string | null;
          tags: string | null;
          seo_title: string | null;
          seo_desc: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          category_id?: string | null;
          product_type: ProductType;
          base_price: number;
          is_active?: boolean;
          is_featured?: boolean;
          is_new?: boolean;
          images?: string | null;
          thumbnail?: string | null;
          tags?: string | null;
          seo_title?: string | null;
          seo_desc?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          category_id?: string | null;
          product_type?: ProductType;
          base_price?: number;
          is_active?: boolean;
          is_featured?: boolean;
          is_new?: boolean;
          images?: string | null;
          thumbnail?: string | null;
          tags?: string | null;
          seo_title?: string | null;
          seo_desc?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      product_items: {
        Row: {
          id: string;
          product_id: string;
          fabric_id: string | null;
          sku: string;
          color: string | null;
          size: string | null;
          price_modifier: number;
          stock_quantity: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          fabric_id?: string | null;
          sku: string;
          color?: string | null;
          size?: string | null;
          price_modifier?: number;
          stock_quantity?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          fabric_id?: string | null;
          sku?: string;
          color?: string | null;
          size?: string | null;
          price_modifier?: number;
          stock_quantity?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      cart_items: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          product_item_id: string | null;
          fabric_id: string | null;
          quantity: number;
          customization: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          product_item_id?: string | null;
          fabric_id?: string | null;
          quantity?: number;
          customization?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string;
          product_item_id?: string | null;
          fabric_id?: string | null;
          quantity?: number;
          customization?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string;
          subtotal: number;
          discount: number;
          tax: number;
          shipping_cost: number;
          total: number;
          payment_status: PaymentStatus;
          payment_method: PaymentMethod | null;
          payment_reference: string | null;
          paid_at: string | null;
          delivery_method: DeliveryMethod;
          delivery_address_id: string | null;
          delivery_notes: string | null;
          delivery_status: DeliveryStatus;
          delivered_at: string | null;
          production_status: ProductionStatus;
          assigned_tailor_id: string | null;
          estimated_ready: string | null;
          actual_ready: string | null;
          status: OrderStatus;
          notes: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          user_id: string;
          subtotal: number;
          discount?: number;
          tax?: number;
          shipping_cost?: number;
          total: number;
          payment_status?: PaymentStatus;
          payment_method?: PaymentMethod | null;
          payment_reference?: string | null;
          paid_at?: string | null;
          delivery_method: DeliveryMethod;
          delivery_address_id?: string | null;
          delivery_notes?: string | null;
          delivery_status?: DeliveryStatus;
          delivered_at?: string | null;
          production_status?: ProductionStatus;
          assigned_tailor_id?: string | null;
          estimated_ready?: string | null;
          actual_ready?: string | null;
          status?: OrderStatus;
          notes?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          user_id?: string;
          subtotal?: number;
          discount?: number;
          tax?: number;
          shipping_cost?: number;
          total?: number;
          payment_status?: PaymentStatus;
          payment_method?: PaymentMethod | null;
          payment_reference?: string | null;
          paid_at?: string | null;
          delivery_method?: DeliveryMethod;
          delivery_address_id?: string | null;
          delivery_notes?: string | null;
          delivery_status?: DeliveryStatus;
          delivered_at?: string | null;
          production_status?: ProductionStatus;
          assigned_tailor_id?: string | null;
          estimated_ready?: string | null;
          actual_ready?: string | null;
          status?: OrderStatus;
          notes?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_item_id: string | null;
          product_name: string;
          product_type: ProductType;
          fabric_name: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
          customization: string | null;
          measurement_id: string | null;
          special_requests: string | null;
          production_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          product_item_id?: string | null;
          product_name: string;
          product_type: ProductType;
          fabric_name?: string | null;
          quantity: number;
          unit_price: number;
          total_price: number;
          customization?: string | null;
          measurement_id?: string | null;
          special_requests?: string | null;
          production_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          product_item_id?: string | null;
          product_name?: string;
          product_type?: ProductType;
          fabric_name?: string | null;
          quantity?: number;
          unit_price?: number;
          total_price?: number;
          customization?: string | null;
          measurement_id?: string | null;
          special_requests?: string | null;
          production_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          user_id: string;
          staff_id: string | null;
          type: AppointmentType;
          scheduled_at: string;
          duration: number;
          status: AppointmentStatus;
          location: string | null;
          address_id: string | null;
          is_virtual: boolean;
          meeting_link: string | null;
          notes: string | null;
          reminder_sent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          staff_id?: string | null;
          type: AppointmentType;
          scheduled_at: string;
          duration?: number;
          status?: AppointmentStatus;
          location?: string | null;
          address_id?: string | null;
          is_virtual?: boolean;
          meeting_link?: string | null;
          notes?: string | null;
          reminder_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          staff_id?: string | null;
          type?: AppointmentType;
          scheduled_at?: string;
          duration?: number;
          status?: AppointmentStatus;
          location?: string | null;
          address_id?: string | null;
          is_virtual?: boolean;
          meeting_link?: string | null;
          notes?: string | null;
          reminder_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      measurements: {
        Row: {
          id: string;
          user_id: string;
          profile_name: string;
          is_default: boolean;
          neck: number | null;
          shoulders: number | null;
          chest: number | null;
          waist: number | null;
          sleeve_length: number | null;
          wrist: number | null;
          back_length: number | null;
          hip: number | null;
          thigh: number | null;
          knee: number | null;
          calf: number | null;
          ankle: number | null;
          inseam: number | null;
          outseam: number | null;
          height: number | null;
          weight: number | null;
          fit_preference: FitType;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          profile_name?: string;
          is_default?: boolean;
          neck?: number | null;
          shoulders?: number | null;
          chest?: number | null;
          waist?: number | null;
          sleeve_length?: number | null;
          wrist?: number | null;
          back_length?: number | null;
          hip?: number | null;
          thigh?: number | null;
          knee?: number | null;
          calf?: number | null;
          ankle?: number | null;
          inseam?: number | null;
          outseam?: number | null;
          height?: number | null;
          weight?: number | null;
          fit_preference?: FitType;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          profile_name?: string;
          is_default?: boolean;
          neck?: number | null;
          shoulders?: number | null;
          chest?: number | null;
          waist?: number | null;
          sleeve_length?: number | null;
          wrist?: number | null;
          back_length?: number | null;
          hip?: number | null;
          thigh?: number | null;
          knee?: number | null;
          calf?: number | null;
          ankle?: number | null;
          inseam?: number | null;
          outseam?: number | null;
          height?: number | null;
          weight?: number | null;
          fit_preference?: FitType;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          label: string | null;
          street: string;
          city: string;
          region: string | null;
          country: string;
          postal_code: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          label?: string | null;
          street: string;
          city: string;
          region?: string | null;
          country?: string;
          postal_code?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          label?: string | null;
          street?: string;
          city?: string;
          region?: string | null;
          country?: string;
          postal_code?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          user_id: string;
          product_id: string | null;
          order_id: string | null;
          rating: number;
          title: string | null;
          comment: string | null;
          images: string | null;
          is_verified: boolean;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id?: string | null;
          order_id?: string | null;
          rating: number;
          title?: string | null;
          comment?: string | null;
          images?: string | null;
          is_verified?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string | null;
          order_id?: string | null;
          rating?: number;
          title?: string | null;
          comment?: string | null;
          images?: string | null;
          is_verified?: boolean;
          is_published?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      wishlists: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_id?: string;
          created_at?: string;
        };
      };
      promotions: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          discount_type: DiscountType;
          discount_value: number;
          min_purchase: number | null;
          max_discount: number | null;
          usage_limit: number | null;
          usage_count: number;
          per_user_limit: number;
          start_date: string;
          end_date: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string | null;
          discount_type: DiscountType;
          discount_value: number;
          min_purchase?: number | null;
          max_discount?: number | null;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number;
          start_date: string;
          end_date: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          discount_type?: DiscountType;
          discount_value?: number;
          min_purchase?: number | null;
          max_discount?: number | null;
          usage_limit?: number | null;
          usage_count?: number;
          per_user_limit?: number;
          start_date?: string;
          end_date?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: UserRole;
      product_type: ProductType;
      fabric_quality: FabricQuality;
      fit_type: FitType;
      order_status: OrderStatus;
      payment_status: PaymentStatus;
      payment_method: PaymentMethod;
      delivery_method: DeliveryMethod;
      delivery_status: DeliveryStatus;
      production_status: ProductionStatus;
      appointment_type: AppointmentType;
      appointment_status: AppointmentStatus;
      discount_type: DiscountType;
    };
  };
}

// Enums
export type UserRole = 'CUSTOMER' | 'ADMIN' | 'TAILOR' | 'STYLIST';
export type ProductType = 'SUIT' | 'SHIRT' | 'TROUSERS' | 'BLAZER' | 'WAISTCOAT' | 'KAFTAN' | 'ACCESSORY';
export type FabricQuality = 'BUDGET' | 'STANDARD' | 'PREMIUM' | 'LUXURY';
export type FitType = 'SLIM' | 'REGULAR' | 'RELAXED';
export type OrderStatus = 'PENDING' | 'CONFIRMED' | 'IN_PRODUCTION' | 'READY' | 'SHIPPED' | 'DELIVERED' | 'COMPLETED' | 'CANCELLED' | 'REFUNDED';
export type PaymentStatus = 'PENDING' | 'DEPOSIT_PAID' | 'PARTIALLY_PAID' | 'PAID' | 'FAILED' | 'REFUNDED';
export type PaymentMethod = 'CARD' | 'MPESA' | 'TIGO_PESA' | 'AIRTEL_MONEY' | 'BANK_TRANSFER' | 'CASH';
export type DeliveryMethod = 'PICKUP' | 'DELIVERY';
export type DeliveryStatus = 'PENDING' | 'PROCESSING' | 'SHIPPED' | 'IN_TRANSIT' | 'DELIVERED';
export type ProductionStatus = 'PENDING' | 'CUTTING' | 'SEWING' | 'FINISHING' | 'QUALITY_CHECK' | 'READY';
export type AppointmentType = 'IN_STORE_FITTING' | 'VIRTUAL_CONSULTATION' | 'MEASUREMENT_SESSION' | 'STYLE_CONSULTATION' | 'PICKUP';
export type AppointmentStatus = 'PENDING' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';
export type DiscountType = 'PERCENTAGE' | 'FIXED_AMOUNT';

// Table types
export type User = Database['public']['Tables']['users']['Row'];
export type Category = Database['public']['Tables']['categories']['Row'];
export type Fabric = Database['public']['Tables']['fabrics']['Row'];
export type Product = Database['public']['Tables']['products']['Row'];
export type ProductItem = Database['public']['Tables']['product_items']['Row'];
export type CartItem = Database['public']['Tables']['cart_items']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderItem = Database['public']['Tables']['order_items']['Row'];
export type Appointment = Database['public']['Tables']['appointments']['Row'];
export type Measurement = Database['public']['Tables']['measurements']['Row'];
export type Address = Database['public']['Tables']['addresses']['Row'];
export type Review = Database['public']['Tables']['reviews']['Row'];
export type Wishlist = Database['public']['Tables']['wishlists']['Row'];
export type Promotion = Database['public']['Tables']['promotions']['Row'];

// Insert types
export type InsertUser = Database['public']['Tables']['users']['Insert'];
export type InsertCategory = Database['public']['Tables']['categories']['Insert'];
export type InsertFabric = Database['public']['Tables']['fabrics']['Insert'];
export type InsertProduct = Database['public']['Tables']['products']['Insert'];
export type InsertProductItem = Database['public']['Tables']['product_items']['Insert'];
export type InsertCartItem = Database['public']['Tables']['cart_items']['Insert'];
export type InsertOrder = Database['public']['Tables']['orders']['Insert'];
export type InsertOrderItem = Database['public']['Tables']['order_items']['Insert'];
export type InsertAppointment = Database['public']['Tables']['appointments']['Insert'];
export type InsertMeasurement = Database['public']['Tables']['measurements']['Insert'];
export type InsertAddress = Database['public']['Tables']['addresses']['Insert'];
export type InsertReview = Database['public']['Tables']['reviews']['Insert'];
export type InsertWishlist = Database['public']['Tables']['wishlists']['Insert'];
export type InsertPromotion = Database['public']['Tables']['promotions']['Insert'];
